services:

  proxy:
    image: nginx:1.28
    container_name: asv-proxy
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./dockerize:/usr/local/bin/dockerize
      - ./503.html:/usr/share/nginx/html/503.html
    command: dockerize -wait tcp://asv-main:5000 -timeout 60s nginx -g "daemon off;"

networks:
  default:
    external: true
    name: mol-mod_default
