services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 8081:8081
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy.conf:/etc/nginx/proxy.conf
      - ./conf.d/molecular.conf:/etc/nginx/conf.d/molecular.conf
      - ./503.html:/usr/share/nginx/html/503.html

networks:
  default:
    external: true
    name: mol-mod_default
