services:

  proxy:
    image: nginx:1.28
    ports:
      - 8081:8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./503.html:/usr/share/nginx/html/503.html

networks:
  default:
    external: true
    name: mol-mod_default
